### ISSUE TITLE
Routes folder empty after generation

### ISSUE THREAD

**Issue by beng94** [ForestAdmin/lumber#110]
I'd like to try out lumber-cli, so I setup a simple Postgres db, with a simple schema, with a single row in it. The generator runs successfully, saying "👍  Hooray, installation success! 👍".

If open up the admin UI, I see my table, but it can't fetch my data. In the console, there's the following error:

> [forest] 🌳🌳🌳  Unexpected error: column books.id does not exist
> SequelizeDatabaseError: column books.id does not exist
>     at Query.formatError (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/lib/dialects/postgres/query.js:351:16)
>     at query.catch.err (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
>     at tryCatcher (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:689:18)
>     at Async._drainQueue (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.Async.drainQueues (/Users/macbookpro/Desktop/lumber_test/monkey/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:781:20)
>     at tryOnImmediate (timers.js:743:5)
>     at processImmediate [as _immediateCallback] (timers.js:714:5)

Looking at the code, it seems evident that the problem is with the missing route.

Any ideas?

**Comment by beng94** [comment]
Just realised, that you use 'forest-express-sequelize' package for the API generation and I won't find the API routes in the routes folder. Do you use the routes folder for anything, or it's just an auto generated folder?
