### ISSUE TITLE
PostgreSQL ltree Data Type Support

### ISSUE THREAD

**Issue by squeakyspacebar** [ForestAdmin/lumber#124]
I'm encountering an issue with relationships where the target model contains an `ltree` column. Since Sequelize does not support `ltree` in its models as far as I am aware, in the model I defined the `ltree` field using `Datatypes.TEXT` instead, as it is the closest data type seems like it would cause the least amount of semantic issues.

However, it causes a problem with the default filtered dropdown widget when attempting to find the row I want to relate. I notice that when I use the filter bar, the following error occurs in the API server output:

```
[forest] 🌳🌳🌳  Unexpected error: function lower(ltree) does not exist
SequelizeDatabaseError: function lower(ltree) does not exist
    at Query.formatError (.../node_modules/sequelize/lib/dialects/postgres/query.js:351:16)
    at query.catch.err (.../node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (.../node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (.../node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (.../node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (.../node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (.../node_modules/sequelize/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (.../node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (.../node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (.../node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

This does not happen if I define the field using a non-string data type, so my guess is that the search widget is finding all of the string fields in the model and attempting to lowercase them all using the database's native functionality.

Thinking through how to solve this while preserving ease-of-use functionality, it does seem to be slightly thorny, but I'm hoping somebody might come up with a decent solution or workaround.

**Comment by arnaudbesnier** [comment]
Hi @squeakyspacebar, 
Sequelize does not look to have any plan to support `ltree` type :/
So your model field type looks to be the best possible so far.

As a workaround, to prevent the search issue on the related model your can declare the list of field you want to use for the search purpose:
```javascript
Liana.collection('myCollection', {
  searchFields: ['myField1', 'myField2'], // NOTICE: The fields you want except the ltree one
});
```

Let me close this issue, feel free to re-open the ticket if the workaround does not work for your use case.

🌲🌲🌲
