### ISSUE TITLE
User friendly error message in case of connection error to the database

### ISSUE THREAD

**Issue by root-io** [ForestAdmin/lumber#132]
Could be nice to add a checklist of why the connection to the database might failed, like:

- Your database is running at 127.0.0.1 on port 5432.
- Your password is correct
...
```
error: 💀  Ouch, cannot connect to the database 💀  due to the following error:
 SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
    at connection.connect.err (/Users/davidrouthieau/Documents/projects/lumber/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:95:24)
    at Client.<anonymous> (/Users/davidrouthieau/Documents/projects/lumber/node_modules/pg/lib/client.js:203:5)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.<anonymous> (/Users/davidrouthieau/Documents/projects/lumber/node_modules/pg/lib/connection.js:86:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by SeyZ** [comment]
@root-io do you have an idea how to do this? I'm not sure Sequelize or even the database itself returns an explicit reason. If you have suggestion, don't hesitate to reopen this issue.
