### ISSUE TITLE
_.contains is not a function

### ISSUE THREAD

**Issue by Antonhansel** [ForestAdmin/lumber#138]
I get this error when I try to see any table

```
[forest] 🌳🌳🌳  Unexpected error: _.contains is not a function
TypeError: _.contains is not a function
    at QueryBuilder.getOrder (/Users/admin/perso/project/cryptoapis/node_modules/forest-express-sequelize/services/query-builder.js:56:39)
    at /Users/admin/perso/project/cryptoapis/node_modules/forest-express-sequelize/services/resources-getter.js:129:31
    at tryCatcher (/Users/admin/perso/project/cryptoapis/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/admin/perso/project/cryptoapis/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/admin/perso/project/cryptoapis/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (/Users/admin/perso/project/cryptoapis/node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (/Users/admin/perso/project/cryptoapis/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/Users/admin/perso/project/cryptoapis/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues (/Users/admin/perso/project/cryptoapis/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
GET /forest/GroupedBalances?fields[...] 500 2.181 ms - 67
```

Maybe this can help:
https://github.com/mgonto/restangular/issues/1298

**Comment by SeyZ** [comment]
@Antonhansel can you paste me the output of the command `npm list` executed on your lumber-generated admin?

**Comment by SeyZ** [comment]
Hey @Antonhansel - it was a regression on the `forest-express-sequelize` package. `contains` alias has been deleted to the newest version of `lodash`.

It's now fixed if your upgrade the `forest-express-sequelize` to the version `2.12.2` in your Lumber generated folder (package.json).

Thanks!
