### ISSUE TITLE
Error on 'lumber update'

### ISSUE THREAD

**Issue by Plovie** [ForestAdmin/lumber#139]
The command `lumber update` crash with the following message : 

`/usr/local/lib/node_modules/lumber-cli/services/db.js:34
        );
        ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/lumber-cli/lumber-update.js:5:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)`

**Comment by SeyZ** [comment]
@Plovie What version of Node are you using?

**Comment by Plovie** [comment]
Hi sorry, you are actually right i was on an previous version for deploying on gcloud function.
