### ISSUE TITLE
cannot update lumber

### ISSUE THREAD

**Issue by jreg11755** [ForestAdmin/lumber#152]
Hi!

I tried to install lumber client using` sudo npm install -g lumber-cli` as it was specified in the official documentation.  (lumber-cli@1.10.2.)
 When I run `lumber update`, I get the following 

`Error: Cannot find module 'parse-database-url'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/lumber-cli/lumber-update.js:9:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3`

any ideas or suggestions? thank you

**Comment by facundofarias** [comment]
@SeyZ I think it might be related to #150 
Thanks!

**Comment by SeyZ** [comment]
Thanks @jreg11755 @facundofarias 
If it's the same issue than the #150 - it's fixed https://github.com/ForestAdmin/lumber/issues/150

Thanks!

**Comment by facundofarias** [comment]
Thanks @SeyZ
