### ISSUE TITLE
Lumber Generate Error

### ISSUE THREAD

**Issue by jasonbpg** [ForestAdmin/lumber#160]
Hi Guys,

I'm having trouble generating a lumber environment. Any idea what could be causing this? 

:~ jasonstockton$ lumber generate
/usr/local/lib/node_modules/lumber-cli/lumber-generate.js:28
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by arnaudbesnier** [comment]
Hey @jasonbpg , which version of Lumber do you currently use?
Also, do you observe a regression or is it the first time you use it?

Thanks for your help.

**Comment by jasonbpg** [comment]
It's the latest version, I've literally just installed it and tried to use it for the first time.

I also tried uninstalling and installing Lumber again with the same error :(

**Comment by jasonbpg** [comment]
Okay, I've found the issue. It seems an out of date version of Node is the cause. 

To update Node I followed the instructions here:
https://stackoverflow.com/questions/11284634/upgrade-node-js-to-the-latest-version-on-mac-os
