### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by BobbyRH** [ForestAdmin/lumber#169]
I need your help, I have problem, Generate Lumber at windows 7 profesional 64 bit with Command Line.
````
D:\Git\hakim>lumber generate
C:\Users\obywie\AppData\Roaming\npm\node_modules\lumber-cli\lumber-generate.js:2
8
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

D:\Git\hakim>
```
`

**Comment by SeyZ** [comment]
What's the version of your Node?

**Comment by BobbyRH** [comment]
> What's the version of your Node?

Node v6.11.3

**Comment by nishantnath** [comment]
Solution:
npm cache clean -f
npm install -g n
n stable

check version (might need reboot)
node -v

npm update -g lumber-cli --save
lumber -V

works now

**Comment by SeyZ** [comment]
Node 8 is required 👍
