### ISSUE TITLE
lumber cli on Windows fails

### ISSUE THREAD

**Issue by jtucker** [ForestAdmin/lumber#18]
After installing on Windows 10 x64 and trying to do any of the commands give the following error:

```
lumber generate
module.js:457
    throw err;
    ^

Error: Cannot find module "C:\Users\users\AppData\Roaming\npm\node_modules\lumber-cli\index-generate"
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

node -v
v6.7.0
npm -v
3.10.7

**Comment by SeyZ** [comment]
@jtucker Thanks for report! Can you confirm me if the version `1.0.7` fixes the issue on Windows? Reopen if the problem still happens. Thank  you!
