### ISSUE TITLE
Erro: $ node ./bin/www

### ISSUE THREAD

**Issue by cristianounix** [ForestAdmin/lumber#24]
~ /project-test/ $ node ./bin/www
~ /project-test/node_modules/express/lib/router/index.js:458
throw new TypeError('Router.use() requires middleware function but got a ' + gettype(fn));
      ^
TypeError: Router.use() requires middleware function but got a Object
    at Function.use (~ /project-test/node_modules/express/lib/router/index.js:458:13)
    at EventEmitter.<anonymous> (~ /project-test/node_modules/express/lib/application.js:219:21)
    at Array.forEach (native)
    at EventEmitter.use (~ /project-test/node_modules/express/lib/application.js:216:7)
    at fs.readdirSync.forEach (~ /project-test/app.js:32:7)
    at Array.forEach (native)
    at Object.<anonymous> (~ /project-test/app.js:31:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

**Comment by SeyZ** [comment]
Duplicate https://github.com/ForestAdmin/lumber/issues/22
