### ISSUE TITLE
Model creation error: A column called 'id' was added to the attributes but not marked with 'primaryKey: true'

### ISSUE THREAD

**Issue by valecarlos** [ForestAdmin/lumber#254]
## Expected behavior

All models are created for different tables

## Actual behavior

Model creation fails, complaining about a column called 'id' added to the attributes but not marked with 'primaryKey: true'

## Failure Logs

```
docker-compose up
| Model creation error: Error: A column called 'id' was added to the attributes of 'products' but not marked with 'primaryKey: true'
| Model creation error: Error: A column called 'id' was added to the attributes of 'subscriptions' but not marked with 'primaryKey: true'
```

## Context

* Lumber Package Version: "lumber-forestadmin": "^1.2.1"
* Database Dialect: PostgreSQL
* Database Version: PostgreSQL 10.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit

**Comment by arnaudbesnier** [comment]
Hi @valecarlos ,
I think this issue is now fixed with the latest lumber version (`v3.3.3` for instance).

Let me close this ticket, but feel free to re-open it I the issue persists.

🌲🌲🌲

**Comment by gfleetwood** [comment]
Getting this error now on Ubuntu 18.04 with Postgres.

```
Creating mithril ... done
Attaching to mithril
mithril | 
mithril | > mithril@0.0.1 start /usr/src/app
mithril | > node ./server.js
mithril | 
mithril | Model creation error: Error: A column called 'id' was added to the attributes of 'databasechangelog' but not marked with 'primaryKey: true'
mithril | /usr/src/app/node_modules/sequelize/lib/associations/base.js:106
mithril |       throw new AssociationError(`You have used the alias ${options.as} in two separate associations. ` +
mithril |       ^
mithril | 
mithril | SequelizeAssociationError: You have used the alias jobGroupQrtzTriggers in two separate associations. Aliased associations must have unique aliases.
mithril |     at new Association (/usr/src/app/node_modules/sequelize/lib/associations/base.js:106:13)
mithril |     at new HasMany (/usr/src/app/node_modules/sequelize/lib/associations/has-many.js:19:5)
mithril |     at Function.hasMany (/usr/src/app/node_modules/sequelize/lib/associations/mixin.js:34:25)
mithril |     at Function.QrtzJobDetails.associate (/usr/src/app/models/qrtz-job-details.js:57:20)
mithril |     at /usr/src/app/models/index.js:39:19
mithril |     at Array.forEach (<anonymous>)
mithril |     at Object.<anonymous> (/usr/src/app/models/index.js:37:17)
mithril |     at Module._compile (internal/modules/cjs/loader.js:778:30)
mithril |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
mithril |     at Module.load (internal/modules/cjs/loader.js:653:32)
mithril |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
mithril |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
mithril |     at Module.require (internal/modules/cjs/loader.js:692:17)
mithril |     at require (internal/modules/cjs/helpers.js:25:18)
mithril |     at Object.<anonymous> (/usr/src/app/routes/activity.js:3:22)
mithril |     at Module._compile (internal/modules/cjs/loader.js:778:30)
mithril |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
mithril |     at Module.load (internal/modules/cjs/loader.js:653:32)
mithril |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
mithril |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
mithril |     at Module.require (internal/modules/cjs/loader.js:692:17)
mithril |     at require (internal/modules/cjs/helpers.js:25:18)
mithril |     at /usr/src/app/node_modules/require-all/index.js:56:46
mithril |     at Array.forEach (<anonymous>)
mithril |     at requireAll (/usr/src/app/node_modules/require-all/index.js:34:9)
mithril |     at Object.<anonymous> (/usr/src/app/app.js:47:1)
mithril |     at Module._compile (internal/modules/cjs/loader.js:778:30)
mithril |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
mithril |     at Module.load (internal/modules/cjs/loader.js:653:32)
mithril |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
mithril |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
mithril |     at Module.require (internal/modules/cjs/loader.js:692:17)
mithril |     at require (internal/modules/cjs/helpers.js:25:18)
mithril |     at Object.<anonymous> (/usr/src/app/server.js:2:13)
mithril | npm ERR! code ELIFECYCLE
mithril | npm ERR! errno 1
mithril | npm ERR! mithril@0.0.1 start: `node ./server.js`
mithril | npm ERR! Exit status 1
mithril | npm ERR! 
mithril | npm ERR! Failed at the mithril@0.0.1 start script.
mithril | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
mithril | 
mithril | npm ERR! A complete log of this run can be found in:
mithril | npm ERR!     /root/.npm/_logs/2020-04-20T13_40_08_357Z-debug.log
mithril exited with code 1
```

**Comment by arnaudbesnier** [comment]
Hi @gfleetwood, do you know the version of the Lumber CLI you used (`lumber --version`) to create your Admin API?

Your `databasechangelog` table schema would help a lot to investigate.
Can you share it with us?

Thanks for your help.

**Comment by gfleetwood** [comment]
@arnaudbesnier I used docker and docker-compose to do the setup and it pulled from [here](https://hub.docker.com/r/forestadmin/lumber). When I created a container from the image it has lumber 3.5.1.

**Comment by edouardjmn** [comment]
Same issue here! 
I'm using lumber 3.6.8

**Comment by edouardjmn** [comment]
Fixed: DB credentials needs write permissions

**Comment by productfrontenddeveloper** [comment]
some problem
```
Model creation error: Error: A column called 'id' was added to the attributes of 'month' but not marked with 'primaryKey: true'
Model creation error: Error: A column called 'id' was added to the attributes of 'town' but not marked with 'primaryKey: true'
```
