### ISSUE TITLE
Unable to start Lumber

### ISSUE THREAD

**Issue by imownbey** [ForestAdmin/lumber#34]
Getting this error:

```
➜  ~/workspace/Bumpers-localhost  node bin/www
/Users/imownbey/workspace/Bumpers-localhost/node_modules/sequelize/lib/associations/belongs-to.js:64
  this.targetKeyField = this.target.rawAttributes[this.targetKey].field || this.targetKey;
                                                                 ^

TypeError: Cannot read property 'field' of undefined
    at new BelongsTo (/Users/imownbey/workspace/Bumpers-localhost/node_modules/sequelize/lib/associations/belongs-to.js:64:66)
    at .belongsTo (/Users/imownbey/workspace/Bumpers-localhost/node_modules/sequelize/lib/associations/mixin.js:106:23)
    at sequelize.define.classMethods.associate (/Users/imownbey/workspace/Bumpers-localhost/models/episode_authors.js:10:15)
    at /Users/imownbey/workspace/Bumpers-localhost/models/index.js:34:19
    at Array.forEach (native)
    at Object.<anonymous> (/Users/imownbey/workspace/Bumpers-localhost/models/index.js:32:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:4% 
```

**Comment by SeyZ** [comment]
Hey @imownbey 

Can you paste me the `belongsTo` relationship (inside the `associate` function) in your model file: `models/episode_authors.js` ?

Thank you!

**Comment by imownbey** [comment]
Model.belongsTo(models.episodes, {
          foreignKey: 'episode_id',
          targetKey: 'episode_id',
          as: 'relepisodes',
        });
        
        Model.belongsTo(models.users, {
          foreignKey: 'user_id',
          targetKey: 'user_id',
          as: 'relusers',
        });

**Comment by SeyZ** [comment]
@imownbey if you temporary comment those lines, is it working?

**Comment by imownbey** [comment]
I then get:

➜  ~/workspace/Bumpers-localhost  node bin/www
/Users/imownbey/workspace/Bumpers-localhost/node_modules/sequelize/lib/associations/belongs-to.js:64
  this.targetKeyField = this.target.rawAttributes[this.targetKey].field || this.targetKey;
                                                                 ^

TypeError: Cannot read property 'field' of undefined
    at new BelongsTo (/Users/imownbey/workspace/Bumpers-localhost/node_modules/sequelize/lib/associations/belongs-to.js:64:66)
    at .belongsTo (/Users/imownbey/workspace/Bumpers-localhost/node_modules/sequelize/lib/associations/mixin.js:106:23)
    at sequelize.define.classMethods.associate (/Users/imownbey/workspace/Bumpers-localhost/models/episodes.js:41:15)
    at /Users/imownbey/workspace/Bumpers-localhost/models/index.js:34:19
    at Array.forEach (native)
    at Object.<anonymous> (/Users/imownbey/workspace/Bumpers-localhost/models/index.js:32:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by SeyZ** [comment]
Ok it seems that the relationships are not well setup. Can you try by commenting the relationships in the file `models/episodes.js`?

**Comment by imownbey** [comment]
➜  ~/workspace/Bumpers-localhost  node bin/www          
/Users/imownbey/workspace/Bumpers-localhost/node_modules/sequelize/lib/associations/belongs-to.js:64
  this.targetKeyField = this.target.rawAttributes[this.targetKey].field || this.targetKey;
                                                                 ^

TypeError: Cannot read property 'field' of undefined
    at new BelongsTo (/Users/imownbey/workspace/Bumpers-localhost/node_modules/sequelize/lib/associations/belongs-to.js:64:66)
    at .belongsTo (/Users/imownbey/workspace/Bumpers-localhost/node_modules/sequelize/lib/associations/mixin.js:106:23)
    at sequelize.define.classMethods.associate (/Users/imownbey/workspace/Bumpers-localhost/models/flags.js:16:15)
    at /Users/imownbey/workspace/Bumpers-localhost/models/index.js:34:19
    at Array.forEach (native)
    at Object.<anonymous> (/Users/imownbey/workspace/Bumpers-localhost/models/index.js:32:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

**Comment by SeyZ** [comment]
ok @imownbey can you try to comment *all* association in all your models :D?

**Comment by imownbey** [comment]
I will probably just go with another solution so no worries. I was interested in just getting enterprise with the integration engineer to not have to deal with this but it seems like that isn't designed for my needs. But seems like this is less turnkey than I was hoping for especially for a non self hosted solution. 

Thanks for trying to help I appreciate it.
