### ISSUE TITLE
Unable to generate

### ISSUE THREAD

**Issue by narengs7** [ForestAdmin/lumber#4]
I was unable to generate or do any other commands, Below is what i get..

`E:\lumberTest>lumber generate
module.js:457
    throw err;
    ^

Error: Cannot find module 'C:\Users\Fred\AppData\Roaming\npm\node_modules\lumber-cli\index-generate'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

**Comment by SeyZ** [comment]
Are you on Windows?

**Comment by narengs7** [comment]
Yes

**Comment by SeyZ** [comment]
@narengs7 can you try again with the latest version Lumber?

**Comment by gahwa** [comment]
Able to run lumber generate but fails after entering project name. Fails on creating the project folder in Windows, possibly due to the code using the forward slash instead of (sic) Windows backslash.

Here is the error output:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by narengs7** [comment]
@SeyZ  It's working and is great.. Thanks...

**Comment by SeyZ** [comment]
Awesome @narengs7 !
