### ISSUE TITLE
PostgreSQL, Generate a new backend application -> Error

### ISSUE THREAD

**Issue by andreyQw** [ForestAdmin/lumber#436]
## Expected behavior

I am trying to generate a new backend application:
$ lumber generate "Fine" --connection-url "postgres://postgres:testpwd@localhost:5432/en_memoir_development"...

## Actual behavior

TODO: What is the current behavior?

## Failure Logs

TODO: Please include any relevant log snippets, if necessary.

## Context

✓ Connecting to your database
✖ Analyzing the database
> Cannot generate your project.
> An unexpected error occurred. Please reach out for help in our Slack community or create a Github issue with following error: SequelizeDatabaseError: syntax error at or near "("
(node:51769) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: syntax error at or near "("
    at Query.formatError (/Users/testuser/.npm-global/lib/node_modules/lumber-cli/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
........
    at processImmediate (internal/timers.js:456:21)
(node:51769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

* Lumber Package Version: 3.5.6
* Database Dialect: PostgreSQL
* Database Version: 9.6.10

**Comment by ontwikkelfabriek** [comment]
same here

**Comment by arnaudbesnier** [comment]
Hi @andreyQw , @ontwikkelfabriek ,

Could you share with us your nodeJS version?

Can you also ensure to run the `generate` command with the latest Lumber version `v3.6.4`?
This version contains a few fixes about PostgreSQL / nodeJS `v14` compatibility.

Any other contextual information specific to your database/project could help us to isolate the issue.

Thanks for your help

**Comment by ontwikkelfabriek** [comment]
> Could you share with us your nodeJS version?
> 
tried 12.18.3 & 10.18.1

> Can you also ensure to run the `generate` command with the latest Lumber version `v3.6.4`?

yes 3.6.4



> Any other contextual information specific to your database/project could help us to isolate the issue.

postgres 9.3.24

no problems with Postgres v9.4

I just used the wizard to install
