### ISSUE TITLE
Unable to npm install

### ISSUE THREAD

**Issue by eyaltoledano** [ForestAdmin/lumber#7]
```
sudo npm install -g lumber-cli
npm http GET https://registry.npmjs.org/lumber-cli
npm http 304 https://registry.npmjs.org/lumber-cli
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/jsonapi-serializer
npm http GET https://registry.npmjs.org/jsonwebtoken
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mysql
npm http GET https://registry.npmjs.org/pg
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/superagent-promise
npm http GET https://registry.npmjs.org/sequelize
npm http GET https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/inquirer
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/jsonapi-serializer
npm http 304 https://registry.npmjs.org/lodash
npm ERR! Error: No compatible version found: inquirer@'^1.2.2'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.2.0","0.2.1","0.1.11","0.1.12","0.2.2","0.2.3","0.2.4","0.2.5","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.4.0","0.4.1","0.5.0","0.5.1","0.6.0","0.7.1","0.7.2","0.7.3","0.8.0","0.8.2","0.8.3","0.8.4","0.8.5","0.9.0","0.10.0","0.10.1","0.11.0","0.11.1","0.11.2","0.11.3","0.11.4","0.12.0","1.0.0","1.0.1","1.0.2","1.0.3","1.1.0","1.1.1","1.1.2","1.1.3","1.2.1","1.2.2","1.2.3"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:674:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:589:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 16.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "lumber-cli"
npm ERR! cwd /Users/Eyal/Documents/code/reviewembedder
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm http 304 https://registry.npmjs.org/jsonwebtoken
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/mysql
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/pg
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/superagent-promise
npm http 304 https://registry.npmjs.org/sequelize
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Eyal/Documents/code/reviewembedder/npm-debug.log
npm ERR! not ok code 0
```

**Comment by SeyZ** [comment]
Hmmm… strange. Can you clear you cache and try again?

    $ sudo npm cache clean
    $ sudo npm install -g lumber-cli

**Comment by eyaltoledano** [comment]
Tried clearing the cache. No go.

```
npm http GET https://registry.npmjs.org/lumber-cli
npm http 200 https://registry.npmjs.org/lumber-cli
npm http GET https://registry.npmjs.org/lumber-cli/-/lumber-cli-1.0.4.tgz
npm http 200 https://registry.npmjs.org/lumber-cli/-/lumber-cli-1.0.4.tgz
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/jsonapi-serializer
npm http GET https://registry.npmjs.org/jsonwebtoken
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mysql
npm http GET https://registry.npmjs.org/pg
npm http GET https://registry.npmjs.org/sequelize
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/superagent-promise
npm http GET https://registry.npmjs.org/winston
npm http 200 https://registry.npmjs.org/chalk
npm ERR! Error: No compatible version found: chalk@'^1.1.3'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.2.0","0.2.1","0.3.0","0.4.0","0.5.0","0.5.1","1.0.0","1.1.0","1.1.1","1.1.2","1.1.3"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:674:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:589:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 16.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "lumber-cli"
npm ERR! cwd /Users/Eyal/Documents/code/reviewembedder
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm http 200 https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/jsonwebtoken
npm http 200 https://registry.npmjs.org/jsonapi-serializer
npm http 200 https://registry.npmjs.org/inquirer
npm http 200 https://registry.npmjs.org/bluebird
npm http 200 https://registry.npmjs.org/mkdirp
npm http 200 https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/superagent-promise
npm http 200 https://registry.npmjs.org/superagent
npm http 200 https://registry.npmjs.org/winston
npm http 200 https://registry.npmjs.org/pg
npm http 200 https://registry.npmjs.org/mysql
npm http 200 https://registry.npmjs.org/sequelize
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Eyal/Documents/code/reviewembedder/npm-debug.log
npm ERR! not ok code 0
```

**Comment by GuillaumeBadi** [comment]
```node -v v0.8.18``` Try to update your node version to a stable release, it might fix it :)

**Comment by SeyZ** [comment]
@eyaltoledano I can't reproduce your problem :( First time, inquirer was the issue and now it's chalk. Can you try to upgrade like @GuillaumeBadi said to a newest version of node (0.8.18 is old now)?

Reopen this issue if the problem still happens.
